server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybooks?serverTimeZone=ADT
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
