insert into books (title, author_id, category_id) values ('Toy Story', 50, 2);
insert into books (title, author_id, category_id) values ('Harmontown', 44, 3);
insert into books (title, author_id, category_id) values ('Legend of Sleepy Hollow, The', 23, 4);
insert into books (title, author_id, category_id) values ('Clone (Womb)', 44, 1);
insert into books (title, author_id, category_id) values ('Who''s the Caboose?', 44, 5);
insert into books (title, author_id, category_id) values ('Them (Ils)', 40, 6);
insert into books (title, author_id, category_id) values ('Grayeagle', 12, 1);
insert into books (title, author_id, category_id) values ('Four Sons', 15, 2);
insert into books (title, author_id, category_id) values ('Drinking Buddies', 13, 6);
insert into books (title, author_id, category_id) values ('Class of Nuke ''Em High', 17, 4);
insert into books (title, author_id, category_id) values ('Rage of Angels: The Story Continues', 24, 4);
insert into books (title, author_id, category_id) values ('Dream Team, The', 39, 2);
insert into books (title, author_id, category_id) values ('Bamboozled', 35, 3);
insert into books (title, author_id, category_id) values ('Wilson', 45, 5);
insert into books (title, author_id, category_id) values ('Ride Lonesome', 10, 4);
insert into books (title, author_id, category_id) values ('Scotland, Pa.', 34, 3);
insert into books (title, author_id, category_id) values ('March of the Movies (Film Parade, The)', 19, 3);
insert into books (title, author_id, category_id) values ('Civic Duty', 39, 5);
insert into books (title, author_id, category_id) values ('52 Pick-Up', 41, 2);
insert into books (title, author_id, category_id) values ('Proposition, The', 19, 4);
insert into books (title, author_id, category_id) values ('Out of Balance: ExxonMobil''s Impact on Climate Change', 42, 2);
insert into books (title, author_id, category_id) values ('Industrial Symphony No. 1: The Dream of the Brokenhearted', 17, 3);
insert into books (title, author_id, category_id) values ('Killjoy 2: Deliverance from Evil', 46, 6);
insert into books (title, author_id, category_id) values ('Get Well Soon', 14, 4);
insert into books (title, author_id, category_id) values ('Bible, The (a.k.a. Bible... In the Beginning, The)', 41, 2);
insert into books (title, author_id, category_id) values ('For Your Consideration', 22, 4);
insert into books (title, author_id, category_id) values ('In Love and War', 32, 2);
insert into books (title, author_id, category_id) values ('Games', 16, 2);
insert into books (title, author_id, category_id) values ('Cause for Alarm!', 4, 1);
insert into books (title, author_id, category_id) values ('Electric Shadows (Meng ying tong nian)', 39, 6);
insert into books (title, author_id, category_id) values ('Incredible Petrified World, The', 38, 4);
insert into books (title, author_id, category_id) values ('Man Who Loved Cat Dancing, The', 28, 2);
insert into books (title, author_id, category_id) values ('Violet & Daisy', 40, 2);
insert into books (title, author_id, category_id) values ('Magic of Ordinary Days, The', 47, 2);
insert into books (title, author_id, category_id) values ('911 in Plane Site', 44, 4);
insert into books (title, author_id, category_id) values ('Dark Lurking, The', 16, 4);
insert into books (title, author_id, category_id) values ('War at Home, The', 31, 3);
insert into books (title, author_id, category_id) values ('Reindeerspotting - Pako joulumaasta', 50, 2);
insert into books (title, author_id, category_id) values ('Miracle in Cell No. 7', 6, 2);
insert into books (title, author_id, category_id) values ('Multiplicity', 48, 5);
insert into books (title, author_id, category_id) values ('Snowblind', 47, 4);
insert into books (title, author_id, category_id) values ('Enemy', 10, 4);
insert into books (title, author_id, category_id) values ('Bowfinger', 6, 4);
insert into books (title, author_id, category_id) values ('Thanks for Sharing', 16, 3);
insert into books (title, author_id, category_id) values ('On the Other Side of the Tracks (De l''autre côté du périph)', 47, 2);
insert into books (title, author_id, category_id) values ('High Noon', 27, 3);
insert into books (title, author_id, category_id) values ('Magnificent Obsession', 4, 5);
insert into books (title, author_id, category_id) values ('Puff, Puff, Pass', 45, 4);
insert into books (title, author_id, category_id) values ('Centre Stage: Turn It Up', 32, 6);
insert into books (title, author_id, category_id) values ('Promise, The (Versprechen, Das)', 16, 3);
insert into books (title, author_id, category_id) values ('Sahara', 29, 2);
insert into books (title, author_id, category_id) values ('Johnny Mad Dog', 22, 3);
insert into books (title, author_id, category_id) values ('Lucky: No Time For Love', 33, 2);
insert into books (title, author_id, category_id) values ('Let''s Make Love', 25, 5);
insert into books (title, author_id, category_id) values ('Letter to Elia, A', 8, 2);
insert into books (title, author_id, category_id) values ('Toys in the Attic', 3, 4);
insert into books (title, author_id, category_id) values ('Vessel of Wrath', 48, 6);
insert into books (title, author_id, category_id) values ('Henry V (Chronicle History of King Henry the Fift with His Battell Fought at Agincourt in France, The)', 41, 1);
insert into books (title, author_id, category_id) values ('Hammer, The', 37, 4);
insert into books (title, author_id, category_id) values ('Tamara', 28, 6);
insert into books (title, author_id, category_id) values ('Split, The', 10, 4);
insert into books (title, author_id, category_id) values ('In the Realm of the Senses (Ai no corrida)', 31, 4);
insert into books (title, author_id, category_id) values ('Shackleton''s Antarctic Adventure', 36, 6);
insert into books (title, author_id, category_id) values ('Storm', 17, 2);
insert into books (title, author_id, category_id) values ('Crazies, The (a.k.a. Code Name: Trixie)', 47, 3);
insert into books (title, author_id, category_id) values ('Fletch Lives', 47, 1);
insert into books (title, author_id, category_id) values ('Northeast', 31, 4);
insert into books (title, author_id, category_id) values ('Man of Iron (Czlowiek z Zelaza)', 40, 2);
insert into books (title, author_id, category_id) values ('High School Hellcats', 28, 2);
insert into books (title, author_id, category_id) values ('Bye Bye, Love', 2, 2);
insert into books (title, author_id, category_id) values ('Last Elvis, The (Último Elvis, El)', 25, 5);
insert into books (title, author_id, category_id) values ('Closure', 20, 3);
insert into books (title, author_id, category_id) values ('Girls Town', 4, 3);
insert into books (title, author_id, category_id) values ('Blonde Ambition', 2, 2);
insert into books (title, author_id, category_id) values ('Meek''s Cutoff', 19, 3);
insert into books (title, author_id, category_id) values ('White House Down', 29, 2);
insert into books (title, author_id, category_id) values ('Songs My Brothers Taught Me', 36, 2);
insert into books (title, author_id, category_id) values ('Kurt Cobain About a Son', 3, 3);
insert into books (title, author_id, category_id) values ('God''s Country', 14, 5);
insert into books (title, author_id, category_id) values ('Zerophilia', 14, 6);
insert into books (title, author_id, category_id) values ('Hustle', 36, 4);
insert into books (title, author_id, category_id) values ('Beast Within, The', 23, 6);
insert into books (title, author_id, category_id) values ('Survival Island (Three)', 1, 1);
insert into books (title, author_id, category_id) values ('Mr. Sardonicus', 22, 2);
insert into books (title, author_id, category_id) values ('I Even Met Happy Gypsies (Skupljaci perja)', 29, 3);
insert into books (title, author_id, category_id) values ('Dominick and Eugene', 22, 4);
insert into books (title, author_id, category_id) values ('Herbie: Fully Loaded', 45, 4);
insert into books (title, author_id, category_id) values ('Derrida', 14, 6);
insert into books (title, author_id, category_id) values ('Repentance', 20, 1);
insert into books (title, author_id, category_id) values ('Alan Partridge: Alpha Papa', 35, 5);
insert into books (title, author_id, category_id) values ('Escape Artist, The', 27, 3);
insert into books (title, author_id, category_id) values ('Don''t Come Knocking', 39, 1);
insert into books (title, author_id, category_id) values ('Fist of Fury (Chinese Connection, The) (Jing wu men)', 11, 5);
insert into books (title, author_id, category_id) values ('Raajneeti', 41, 2);
insert into books (title, author_id, category_id) values ('Italian Job, The', 7, 4);
insert into books (title, author_id, category_id) values ('Serena', 42, 1);
insert into books (title, author_id, category_id) values ('Blame It on the Bellboy', 20, 6);
insert into books (title, author_id, category_id) values ('Green Lantern', 36, 3);
insert into books (title, author_id, category_id) values ('King & Country', 26, 1);
insert into books (title, author_id, category_id) values ('Incredible Burt Wonderstone, The', 46, 2);